import pybase64
import base64 
import requests
import binascii
import os


def decode_base64(encoded):

    decoded = ''
    for encoding in ['utf-8', 'iso-8859-1']:
        try:
            decoded = pybase64.b64decode(encoded + b'=' * (-len(encoded) % 4)).decode(encoding)
            break
        except (UnicodeDecodeError, binascii.Error):
            pass
    return decoded


def generate_v2ray_configs(decoded_data):

    configs = []

    for config in decoded_data:
        configs.append(config)

    sorted_configs = sorted(configs)

    return sorted_configs


def decode_links(links):

    decoded_data = []

    for link in links:
        response = requests.get(link)
        encoded_bytes = response.content
        decoded_text = decode_base64(encoded_bytes)
        decoded_data.append(decoded_text)

    sorted_configs = generate_v2ray_configs(decoded_data)

    return sorted_configs


def decode_dir_links(dir_links):


    decoded_dir_links = []

    for link in dir_links:
        response = requests.get(link)
        decoded_text = response.text
        decoded_dir_links.append(decoded_text)

    return decoded_dir_links


def main():
    links = [
'http://141.147.161.50:12580/clash/proxies',
'http://150.230.195.209:12580/clash/proxies',
'http://155.248.172.106:12580/clash/proxies',
'http://172.245.30.41/clash.yaml',
'http://175.178.182.178:12580/clash/proxies',
'http://66.42.50.118:12580/clash/proxies',
'http://beetle.lander.work/clash/proxies',
'http://weoknow.com/data/dayupdate/1/z.txt',
'http://weoknow.com/data/dayupdate/2/z.txt',
'http://www.xrayvip.com/free.txt',
'https://16d33466.madarefilterchi.pages.dev/sub/89b3cbba-e6ac-485a-9481-976a0415eab9#MadareFilterchi',
'https://41f8c935.kakq-panel3.pages.dev/sub/89b3cbba-e6ac-485a-9481-976a0415eab9#BPB-Normal',
'https://9527521.xyz/pubconfig/YCw0l6R3PoDbGFq5',
'https://bitbucket.org/huwo1/proxy_nodes/raw/f31ca9ec67b84071515729ff45b011b6b09c10f2/clash.yaml',
'https://bitbucket.org/huwo1/proxy_nodes/raw/f31ca9ec67b84071515729ff45b011b6b09c10f2/proxy.md',
'https://bitbucket.org/huwo1/proxy_nodes/raw/f31ca9ec67b84071515729ff45b011b6b09c10f2/ss.md',
'https://bitbucket.org/huwo1/proxy_nodes/raw/f31ca9ec67b84071515729ff45b011b6b09c10f2/trojan.md',
'https://bitbucket.org/huwo1/proxy_nodes/raw/f31ca9ec67b84071515729ff45b011b6b09c10f2/vmess.md',
'https://chromego-sub.netlify.app/sub/merged_proxies_new.yaml',
'https://clash.221207.xyz/pubclashyaml',
'https://clashe.eu.org/clash/proxies',
'https://dub.sh/kkovokkk',
'https://fastly.jsdelivr.net/gh/peasoft/NoMoreWalls@master/list.txt',
'https://fragment-freevpnhomes-subscription.meshkintaj.homes',
'https://gcore.jsdelivr.net/gh/peasoft/NoMoreWalls@master/list.txt',
'https://ghostcc.cc/ss.cn/cn.ovg',
'https://iwxf.netlify.app',
'https://jiang.netlify.app',
'https://miner.isherv.in',
'https://muma16fx.netlify.app',
'https://my5353.com/bmCUK',
'https://nekocandy.pages.dev/sub',
'https://proxy.crazygeeky.com/clash/proxies',
'https://proxy.fldhhhhhh.top/clash/proxies',
'https://proxypool.link/clash/proxies',
'https://proxypool.link/sip002/sub',
'https://proxypool.link/trojan/sub',
'https://proxypool.link/vmess/sub',
'https://proxypool1999.banyunxiaoxi.icu/clash/proxies',
'https://pxypool.131433.xyz/clash/proxies',
'https://shadowmere.akiel.dev/api/b64sub',
'https://sub.5112233.xyz/auto',
'https://sub.reajason.eu.org/clash.yaml',
'https://sub.xn--9sw509f.eu.org/auto',
'https://subs.zeabur.app/clash',
'https://tsutsu.top/JEmV1o5',
'https://v2ray.neocities.org/v2ray.txt',
'https://vpn.fail/free-proxy/v2ray',
'https://www.xrayvip.com/free.txt',
'https://www.xrayvip.com/free.yaml',
'https://www.youneed.win/free-ss',
'https://youlianboshi.netlify.app',
'https://yugogo.xyz/?p=1117',
'https://raw.githubusercontent.com/qjlxg/V2rayCollector/main/sub/mix',
'https://sub.sharecentre.online/sub',
'https://github.com/qjlxg/ss/raw/refs/heads/master/list_raw.txt',
'https://github.com/adafhu/laya/raw/master/Eternity',
'https://github.com/adafhu/laya/raw/master/Eternity.yaml',
'https://github.com/imyaoxp/nodes/raw/main/Eternity.yaml',
'https://github.com/LalatinaHub/Mineral/raw/refs/heads/master/result/nodes',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/hysteria.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/hysteria2.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/hy2.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/ss.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/ssr.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/trojan.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/tuic.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/vless.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/vmess.txt',
'https://github.com/qjlxg/hy2/raw/refs/heads/main/splitted/vmess',
'https://github.com/qjlxg/hy2/raw/refs/heads/main/splitted/vless',
'https://github.com/qjlxg/hy2/raw/refs/heads/main/splitted/trojan',
'https://github.com/qjlxg/hy2/raw/refs/heads/main/splitted/ss',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/v2',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/tr',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/ssr',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/ss',
'https://github.com/qjlxg/Ray/raw/main/config.txt',
'https://github.com/qjlxg/aggregator/raw/refs/heads/main/data/clash.yaml',
'https://github.com/qjlxg/proxy-minging/raw/refs/heads/main/v2ray.txt',
'https://github.com/qjlxg/py/raw/refs/heads/main/data/clash.yaml',
'https://github.com/dimzon/scaling-sniffle/raw/refs/heads/main/all-sort.txt',
'https://github.com/dimzon/scaling-sniffle/raw/refs/heads/main/all-ip-resolve-sort.txt',
'https://github.com/dimzon/scaling-sniffle/raw/refs/heads/main/all-domains-sort.txt',
'https://github.com/dimzon/scaling-sniffle/raw/refs/heads/main/all-domains-dedup-sort.txt',
'https://github.com/qjlxg/GO_V2rayCollector/raw/refs/heads/main/vmess_iran.txt',
'https://github.com/qjlxg/GO_V2rayCollector/raw/refs/heads/main/vless_iran.txt',
'https://github.com/qjlxg/TrojanLinks/raw/refs/heads/master/links/ssr',
'https://github.com/qjlxg/free-node/raw/refs/heads/main/public',
'https://github.com/qjlxg/TrojanLinks/raw/refs/heads/master/links/trojan',
'https://github.com/qjlxg/TrojanLinks/raw/refs/heads/master/links/vless',
'https://github.com/qjlxg/TrojanLinks/raw/refs/heads/master/links/vmess',
'https://github.com/vxiaov/free_proxies/raw/refs/heads/main/clash/clash.provider.yaml',
'https://github.com/qjlxg/GO_V2rayCollector/raw/refs/heads/main/trojan_iran.txt',
'https://github.com/qjlxg/GO_V2rayCollector/raw/refs/heads/main/ss_iran.txt',
'https://github.com/qjlxg/GO_V2rayCollector/raw/refs/heads/main/mixed_iran.txt',
'https://github.com/qjlxg/v2ray-worker-sub/raw/refs/heads/master/spd/splitted/trojan.txt',
'https://github.com/qjlxg/v2ray-worker-sub/raw/refs/heads/master/spd/splitted/vmess.txt',
'https://github.com/qjlxg/v2ray-worker-sub/raw/refs/heads/master/spd/splitted/ss.txt',
'https://ghproxy.com//raw.githubusercontent.com/yaney01/Yaney01/main/yaney_01',
'https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml',
'https://gitlab.com/mfuu/v2ray/-/raw/master/clash.yaml',
'https://gitlab.com/univstar1/v2ray/-/raw/main/data/clash/general.yaml',
'https://hiddify-freevpnhomes-subscription.meshkintaj.homes',
'https://hin.isherv.in/#@proxy_kafee%20mci%20sub%204',
'https://raw.github.com/Lewis-1217/FreeNodes/main/bpjzx1',
'https://github.com/Space-00/V2ray_collector/raw/refs/heads/main/config.txt',
'https://github.com/9Knight9n/v2ray-aggregator/raw/refs/heads/main/merged_24h.txt',
'https://raw.githubusercontent.com/245237866/v2rayn/main/everydaynode',
'https://raw.githubusercontent.com/3yed-61/V2rayCollector/main/sub/vmess',
'https://raw.githubusercontent.com/69z1zfw2fly/fly/main/2.yaml',
'https://raw.githubusercontent.com/a313132121/v2rayn/main/everydaynode',
'https://raw.githubusercontent.com/abshare/abshare.github.io/main/README.md',
'https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.txt',
'https://raw.githubusercontent.com/adiwzx/freenode/main/adispeed.yml',
'https://raw.githubusercontent.com/adminaliang/v2ray/main/v2ray',
'https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml',
'https://raw.githubusercontent.com/aiboboxx/kexueshangwang/main/README.md',
'https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/README.md',
'https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2',
'https://raw.githubusercontent.com/Airuop/cross/master/Eternity',
'https://raw.githubusercontent.com/AlienVPN402/AlienVPN402-subscribe-servers-sing-box/main/index.html',
'https://raw.githubusercontent.com/AlienVPN402/Clash-Subscribe/main/index.html',
'https://raw.githubusercontent.com/AlienVPN402/SFA-Config-Servers/main/index.html',
'https://raw.githubusercontent.com/AlienVPN402/Surfboard-Subscribe/main/index.html',
'https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/server.txt',
'https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/sub.txt',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/1/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash.meta2/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash/1/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash/13/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash/2/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash/3/config.yaml',
'https://raw.githubusercontent.com/Alvin9999/pac2/master/clash/config.yaml',
'https://raw.githubusercontent.com/amirhosein24/v2ray-config-farmer/main/zout.txt',
'https://raw.githubusercontent.com/Amirinventor2010/warp-on-hiddify/main/gulagVPN',
'https://raw.githubusercontent.com/anorika77/v2ray-subscribe/main/README.md',
'https://raw.githubusercontent.com/asakura42/vss/master/output.txt',
'https://raw.githubusercontent.com/Ashkan-m/v2ray/main/Sub.txt',
'https://raw.githubusercontent.com/au3300/aggregator/main/data/clash.yaml',
'https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/all',
'https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/ss',
'https://raw.githubusercontent.com/azadiazinjamigzare/Hiddify/main/Sub',
'https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet_iOS.txt',
'https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet_META_IRAN-Direct.yml',
'https://raw.githubusercontent.com/azavaxhuman/Quick_Warp_on_Warp/main/install.sh',
'https://raw.githubusercontent.com/baip01/clash/main/clash',
'https://raw.githubusercontent.com/baip01/yhkj/main/v2ray',
'https://raw.githubusercontent.com/baipiao0/baipiao02/main/v2ray',
'https://raw.githubusercontent.com/bamdad23/testes/main/Hysteria2_IP4_%26_IP6',
'https://raw.githubusercontent.com/bamdad23/testes/main/IIAFP',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/blues.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/kkzui.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/merged.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/nodefree.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/v2rayshare.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/wenode.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/yudou66.txt',
'https://raw.githubusercontent.com/Barabama/FreeNodes/master/nodes/zyfxs.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_Sub.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/ss.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/trojan.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vless.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Splitted-By-Protocol/vmess.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub1.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub2.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub3.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub4.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub5.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub6.txt',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/Sub7.txt',
'https://raw.githubusercontent.com/bingoYB/node_processing/main/dist/all.yaml',
'https://raw.githubusercontent.com/budamu/clashconfig/main/clash.yaml',
'https://raw.githubusercontent.com/budamu/clashconfig/main/v2ray.txt',
'https://raw.githubusercontent.com/budamu/clashconfig/main/v2ray2.txt',
'https://raw.githubusercontent.com/BUTUbird/ClashPoint/main/application.yaml',
'https://raw.githubusercontent.com/caijh/FreeProxiesScraper/main/README.md',
'https://raw.githubusercontent.com/ccnndwa/SSR/main/SSR',
'https://raw.githubusercontent.com/cdp2020/v2ray/master/README.md',
'https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.txt',
'https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml',
'https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list_raw.txt',
'https://raw.githubusercontent.com/chfchf0306/clash/main/clash',
'https://raw.githubusercontent.com/chfchf0306/jeidian4.18/main/4.18',
'https://raw.githubusercontent.com/chongdong1230/dxz/main/clash',
'https://raw.githubusercontent.com/clashconfig/online/main/Dark_Base.txt',
'https://raw.githubusercontent.com/codingbox/Free-Node-Merge/main/node.txt',
'https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/main/raw/tuic%20%26%20hy2.txt',
'https://raw.githubusercontent.com/Creativveb/v2configs/main/updated',
'https://raw.githubusercontent.com/cxr9912/cxr2022/main/free.yaml',
'https://raw.githubusercontent.com/cxr9912/cxr2022/main/ss.yaml',
'https://raw.githubusercontent.com/cxr9912/cxr2022/main/vmess.yaml',
'https://raw.githubusercontent.com/dalazhi/v2ray/main/v2ray%E8%AE%A2%E9%98%85',
'https://raw.githubusercontent.com/Daphnemgt/jiedian/main/v2ray',
'https://raw.githubusercontent.com/deepinor/v2ray_luck/master/sub.txt',
'https://raw.githubusercontent.com/dimzon/scaling-sniffle/main/unknown.lst',
'https://raw.githubusercontent.com/dongchengjie/airport/main/subs/_pool.yaml',
'https://raw.githubusercontent.com/dongchengjie/proxy_workers/main/subs/fromzero.yaml',
'https://raw.githubusercontent.com/dongchengjie/proxy_workers/main/subs/shunfeng.yaml',
'https://raw.githubusercontent.com/dongchengjie/proxy_workers/main/subs/yudou.yaml',
'https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml',
'https://raw.githubusercontent.com/du5/free/master/sub.list',
'https://raw.githubusercontent.com/Ennzo0/V2ray/main/all.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/France/config.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/Germany/config.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/Ireland/config.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/Sweden/config.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/United%20Kingdom/config.txt',
'https://raw.githubusercontent.com/Epodonios/bulk-xray-v2ray-vless-vmess-...-configs/main/sub/United%20States/config.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list1.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list2.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list3.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list4.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list5.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Config%20list6.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/ss.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/trojan.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vmess.txt',
'https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml',
'https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt',
'https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml',
'https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/v2ray.txt',
'https://raw.githubusercontent.com/feng-1995/5.8-2/main/README.md',
'https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/clash_sub.yaml',
'https://raw.githubusercontent.com/firefoxmmx2/v2rayshare_subcription/main/subscription/vray_sub.txt',
'https://raw.githubusercontent.com/FNET00bot/FNET00BOT/Config/App/BeVPN',
'https://raw.githubusercontent.com/FNET00bot/FNET00BOT/Config/Main',
'https://raw.githubusercontent.com/free18/v2ray/main/Clash.yaml',
'https://raw.githubusercontent.com/free18/v2ray/main/v2ray.txt',
'https://raw.githubusercontent.com/freebaipiao/freebaipiao/main/freebaipiao.yaml',
'https://raw.githubusercontent.com/freebaipiao/freebaipiao/main/freebaipiaov2.txt',
'https://raw.githubusercontent.com/freefq/free/master/README.md',
'https://raw.githubusercontent.com/freefq/free/master/v2',
'https://raw.githubusercontent.com/gffice/runproxypool123/master/docs/clash/proxies',
'https://raw.githubusercontent.com/gitbigg/permalink/main/subscribe',
'https://raw.githubusercontent.com/githubvpn007/v2rayNvpn/main/README.md',
'https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml',
'https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml#@iranargo%20sub%20mci%201',
'https://raw.githubusercontent.com/gtang8/SubCrawler/main/sub/share/all',
'https://raw.githubusercontent.com/HakurouKen/free-node/main/public',
'https://raw.githubusercontent.com/HenryPorternew/sbs/main/ssb/sw',
'https://raw.githubusercontent.com/hicloudi/officialinquire/main/README.md',
'https://raw.githubusercontent.com/hkaa0/link/main/sub/v2ray',
'https://raw.githubusercontent.com/hkaa0/permalink/e8f97142d083c0f5dac55af7b6531b300f273b4d/proxy/V2ray',
'https://raw.githubusercontent.com/hkpc/V2ray-Configs/main/All_Configs_Sub.txt',
'https://raw.githubusercontent.com/holms2012/vtor/main/shj2.txt',
'https://raw.githubusercontent.com/hotsymbol/vpnsetting/master/v2rayopen',
'https://raw.githubusercontent.com/hsb4657/v2ray/main/lastest.txt',
'https://raw.githubusercontent.com/huaxinCLUB/NodeSpider/master/newYaml/mattkaydiary.yaml',
'https://raw.githubusercontent.com/huaxinCLUB/NodeSpider/master/newYaml/newestWB.yaml',
'https://raw.githubusercontent.com/huaxinCLUB/NodeSpider/master/newYaml/newestYT.yaml',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/ss',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/ss_with_plugin',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/ssr',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/temporary',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/trojan',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/vless',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/vmess',
'https://raw.githubusercontent.com/Huibq/TrojanLinks/master/links/vmess#ignore=vmess',
'https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/shadowsocks',
'https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/trojan',
'https://raw.githubusercontent.com/iboxz/free-v2ray-collector/main/main/vless',
'https://raw.githubusercontent.com/igeekshare/GeekshareFreeNode/main/clash/Geekshare.yaml',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/Hamrahaval',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/HY%20%26%20TU',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/Irancell',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/Mokhaberat',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/Telegram',
'https://raw.githubusercontent.com/ImMyron/V2ray/main/Web',
'https://raw.githubusercontent.com/imohammadkhalili/V2RAY/main/Mkhalili',
'https://raw.githubusercontent.com/IranianCypherpunks/SingBox/main/Sub',
'https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/hiddify/mix',
'https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/location/base64/%F0%9F%87%A9%F0%9F%87%AA%20DE#',
'https://raw.githubusercontent.com/itsyebekhe/HiN-VPN/main/subscription/normal/mix',
'https://raw.githubusercontent.com/itxve/fetch-clash-node/main/node/ClashNode.yaml',
'https://raw.githubusercontent.com/iwxf/free-v2ray/master/index.html',
'https://raw.githubusercontent.com/Jason05211211/Freerocket/main/freessr',
'https://raw.githubusercontent.com/Jia-Pingwa/free-v2ray-merge/main/output.txt',
'https://raw.githubusercontent.com/JieErJingFu/FreeNodesV2RayorTrojan_20210113-/main/EncryptedFreeNodes.txt',
'https://raw.githubusercontent.com/jikelonglie/meskell/main/meskell',
'https://raw.githubusercontent.com/jiquanxiang/abc/main/v7',
'https://raw.githubusercontent.com/jkchen3/speedo4601.ga/main/README.md',
'https://raw.githubusercontent.com/jkchen3/speedo4601.ml/main/README.md',
'https://raw.githubusercontent.com/jkchen3/workers/main/README.md',
'https://raw.githubusercontent.com/jkchen3/xray/main/README.md',
'https://raw.githubusercontent.com/Junely/clash/main/template3.yaml',
'https://raw.githubusercontent.com/kaoxindalao/v2raycheshi/main/v2raycheshi',
'https://raw.githubusercontent.com/kazabelica/Optimized-Server-List/main/ping-all.yaml',
'https://raw.githubusercontent.com/Kenny-Bob/DIANDIAN/main/point',
'https://raw.githubusercontent.com/kevin-wud/v2ray-node/main/clash.yaml',
'https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/b64mix.txt',
'https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/b64vless.txt',
'https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/mix.txt',
'https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/vless.txt',
'https://raw.githubusercontent.com/lagzian/SS-Collector/main/mix_clash.yaml',
'https://raw.githubusercontent.com/LalatinaHub/Mineral/master/result/nodes',
'https://raw.githubusercontent.com/lanfxx/clashtest/main/clash0221',
'https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/ss',
'https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/tr',
'https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/v2',
'https://raw.githubusercontent.com/Leon406/SubCrawler/master/sub/share/vless',
'https://raw.githubusercontent.com/Lewis-1217/FreeNodes/main/bpjzx1',
'https://raw.githubusercontent.com/lflflf999/0516/main/BX-JD',
'https://raw.githubusercontent.com/liketolivefree/kobabi/main/sub_all.txt',
'https://raw.githubusercontent.com/LonUp/NodeList/main/Clash/Node/Latest.yaml',
'https://raw.githubusercontent.com/LonUp/NodeList/main/Clash/Node/Latest_Meta.yaml',
'https://raw.githubusercontent.com/LonUp/NodeList/main/V2RAY/Latest.txt',
'https://raw.githubusercontent.com/LonUp/NodeList/main/V2RAY/Latest_base64.txt',
'https://raw.githubusercontent.com/Lukeehujt/Clash_node/master/config.yaml',
'https://raw.githubusercontent.com/luxl-1379/merge/77247d23def72b25226dfa741614e9b07a569c72/sub/sub_merge_base64.txt',
'https://raw.githubusercontent.com/luxl-1379/merge/main/sub/sub_merge_base64.txt',
'https://raw.githubusercontent.com/luxl-1379/merge/master/sub/list/24.txt',
'https://raw.githubusercontent.com/luxl-1379/merge/master/sub/list/38.txt',
'https://raw.githubusercontent.com/luxl-1379/merge/master/sub/sub_merge.txt',
'https://raw.githubusercontent.com/luxl-1379/merge/master/sub/sub_merge_base64.txt',
'https://raw.githubusercontent.com/M450ud/PrList/main/dsl.txt',
'https://raw.githubusercontent.com/M450ud/PrList/main/prx.txt',
'https://raw.githubusercontent.com/Mahanfix/v2rayvpn/main/mahanfix',
'https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt',
'https://raw.githubusercontent.com/mahdibland/get_v2/main/pub/combine.yaml',
'https://raw.githubusercontent.com/mahdibland/get_v2/main/pub/Matsuri',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/EternityAir.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/splitted/ss.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/splitted/ssr.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/splitted/trojan.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/splitted/vmess.txt',
'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/sub_merge.txt',
'https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/airport_merge_base64.txt',
'https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/airport_sub_merge.txt',
'https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge.txt',
'https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_base64.txt',
'https://raw.githubusercontent.com/mahdibland/SSAggregator/master/sub/sub_merge_yaml.yml',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/EternityAir',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/EternityAir.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/EternityBase',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/airport_merge_base64.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/airport_sub_merge.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/ss.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/ssr.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/trojan.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/splitted/vmess.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt',
'https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_yaml.yml',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_1.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_2.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_3.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mci/sub_4.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_1.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_2.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_3.txt',
'https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/main/mtn/sub_4.txt',
'https://raw.githubusercontent.com/mermeroo/Loon/main/node',
'https://raw.githubusercontent.com/mfuu/v2ray/b652291a32e61560264df75512cd26e5cfea7e98/merge/merge.txt',
'https://raw.githubusercontent.com/mfuu/v2ray/master/merge/merge.txt',
'https://raw.githubusercontent.com/mfuu/v2ray/master/merge/merge_base64.txt',
'https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/hysteriabase64',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/mix',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/ss',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/ssbase64',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/trojanbase64',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/tuicbase64',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless',
'https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vmess',
'https://raw.githubusercontent.com/mheidari98/.proxy/main/ss',
'https://raw.githubusercontent.com/mheidari98/.proxy/main/vmess',
'https://raw.githubusercontent.com/miladtahanian/V2Collector/main/mixed_iran.txt',
'https://raw.githubusercontent.com/miladtahanian/V2Collector/main/ss_iran.txt',
'https://raw.githubusercontent.com/miladtahanian/V2Collector/main/trojan_iran.txt',
'https://raw.githubusercontent.com/miladtahanian/V2Collector/main/vless_iran.txt',
'https://raw.githubusercontent.com/miladtahanian/V2Collector/main/vmess_iran.txt',
'https://raw.githubusercontent.com/miladtahanian/V2RayCFGDumper/main/config.txt',
'https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml',
'https://raw.githubusercontent.com/MiSaturo/WarpScanner/main/point/endip.sh',
'https://raw.githubusercontent.com/misersun/config002/main/config_all.yaml',
'https://raw.githubusercontent.com/misersun/config003/main/config_all.yaml',
'https://raw.githubusercontent.com/misersun/config003/main/config_all_game.yaml',
'https://raw.githubusercontent.com/misersun/config003/main/config_all_quest.yaml',
'https://raw.githubusercontent.com/mksshare/mksshare.github.io/main/README.md',
'https://raw.githubusercontent.com/mlabalabala/v2ray-node/main/nodefree_nodes_mod.txt',
'https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vless.txt',
'https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vmess.txt',
'https://raw.githubusercontent.com/MOnday9907/v2ray/main/v2ray.txt',
'https://raw.githubusercontent.com/money-fly/subaddress/main/vmess.txt',
'https://raw.githubusercontent.com/moneyfly1/sublist/main/clash.yml',
'https://raw.githubusercontent.com/mostafasadeghifar/v2ray-config/main/config_file.txt',
'https://raw.githubusercontent.com/Mr8AHAL/v2ray/main/SERVER.txt',
'https://raw.githubusercontent.com/mraliasadi8831/Subscription-/main/profiles.txt',
'https://raw.githubusercontent.com/Mr-Amirr-00/Sub-Config-V2ray/Config/Export-APP-FastRay',
'https://raw.githubusercontent.com/Mr-Amirr-00/Sub-Config-V2ray/Config/Export-APP-GreenNet',
'https://raw.githubusercontent.com/Mr-Amirr-00/Sub-Config-V2ray/Config/Export-APP-HotVPN',
'https://raw.githubusercontent.com/Mr-Amirr-00/Sub-Config-V2ray/Config/Renamed-config-channel-workers',
'https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/actives.txt',
'https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/all.txt',
'https://raw.githubusercontent.com/MrPooyaX/SansorchiFucker/main/data.txt',
'https://raw.githubusercontent.com/MrPooyaX/VpnsFucking/main/Shenzo.txt',
'https://raw.githubusercontent.com/mrvcoder/V2rayCollector/main/mixed_iran.txt',
'https://raw.githubusercontent.com/mrvcoder/V2rayCollector/main/ss_iran.txt',
'https://raw.githubusercontent.com/mrvcoder/V2rayCollector/main/trojan_iran.txt',
'https://raw.githubusercontent.com/mrvcoder/V2rayCollector/main/vless_iran.txt',
'https://raw.githubusercontent.com/mrvcoder/V2rayCollector/main/vmess_iran.txt',
'https://raw.githubusercontent.com/mshojaei77/v2rayAuto/main/mix',
'https://raw.githubusercontent.com/nameless255/shadow/main/shadow.txt',
'https://raw.githubusercontent.com/nasheep/FreeNode/main/clash/PlayLab',
'https://raw.githubusercontent.com/nasheep/FreeNode/main/v2ray/PlayLab',
# 'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/all.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/all-hs-proxy.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/default.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/http-proxy.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/hys-tuic.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/lt-sub.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/lt-sub-all.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/my.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/ru.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/ru-arch.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/socks-proxy.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/speed.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/tmp1.txt',
'https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/tmp3.txt',
'https://raw.githubusercontent.com/ndsphonemy/TG-Proxy-Parser/main/config-tg.txt',
'https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml',
'https://raw.githubusercontent.com/NicProxy/V2ray/main/configs',
'https://raw.githubusercontent.com/NiREvil/vless/main/hiddify/WarpOnWarp.json',
'https://raw.githubusercontent.com/NiREvil/vless/main/sub/clash-meta.yml',
'https://raw.githubusercontent.com/NiREvil/vless/main/sub/freedom',
'https://raw.githubusercontent.com/NiREvil/vless/main/sub/SSTime',
'https://raw.githubusercontent.com/NiREvil/vless/main/sub/wireguardn',
'https://raw.githubusercontent.com/NiREvil/vless/main/sub/wireguardv',
'https://raw.githubusercontent.com/norvip/azad/main/sub.txt',
'https://raw.githubusercontent.com/PangTouY00/Auto_proxy/main/Long_term_subscription_num',
'https://raw.githubusercontent.com/parkerpa/zypjj/main/clash',
'https://raw.githubusercontent.com/Pawdroid/Free-servers/main/README.md',
'https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt',
'https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml',
'https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list_raw.txt',
'https://raw.githubusercontent.com/pojiezhiyuanjun/freev2/master/1225.txt',
'https://raw.githubusercontent.com/proSSHvpn/proSSHvpn/main/sub',
'https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/http/data.txt',
'https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks4/data.txt',
'https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/protocols/socks5/data.txt',
'https://raw.githubusercontent.com/qjlxg/aggregator/main/data/clash.yaml',
'https://raw.githubusercontent.com/QQnight/SubCrawler/main/sub/share/all',
'https://raw.githubusercontent.com/RaymondHarris971/ssrsub/master/9a075bdee5.txt',
'https://raw.githubusercontent.com/renyige1314/CLASH/main/CLASH',
'https://raw.githubusercontent.com/resasanian/Mirza/main/best',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-all.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-ss.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-ssr.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-trojan.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-vless.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/mirza-vmess.txt',
'https://raw.githubusercontent.com/resasanian/Mirza/main/ss',
'https://raw.githubusercontent.com/resasanian/Mirza/main/sub',
'https://raw.githubusercontent.com/resasanian/Mirza/main/trojan',
'https://raw.githubusercontent.com/resasanian/Mirza/main/vmess',
'https://raw.githubusercontent.com/Reza-sal/shervin/main/MCI',
'https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash',
'https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub',
'https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/cfmem.yaml',
'https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/changfengoss.yaml',
'https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/combine.yaml',
'https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml',
'https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/v2ray',
'https://raw.githubusercontent.com/SamanValipour1/My-v2ray-configs/main/MySub.txt',
'https://raw.githubusercontent.com/sami-soft/v2rayN_proxy/main/new1.txt',
'https://raw.githubusercontent.com/sangowd/free_doom/main/mattkay.txt',
'https://raw.githubusercontent.com/sangowd/free_doom/main/xiaoqi.txt',
'https://raw.githubusercontent.com/SANYIMOE/VPN-free/master/sub',
'https://raw.githubusercontent.com/sarinaesmailzadeh/V2Hub/main/merged',
'https://raw.githubusercontent.com/sarinaesmailzadeh/V2Hub/main/merged_base64',
'https://raw.githubusercontent.com/sh3d0ww02f/sh3d0ww02f.github.io/main/ss.config',
'https://raw.githubusercontent.com/sh3d0ww02f/sh3d0ww02f.github.io/main/ssr.config',
'https://raw.githubusercontent.com/sh3d0ww02f/sh3d0ww02f.github.io/main/trojan.config',
'https://raw.githubusercontent.com/sh3d0ww02f/sh3d0ww02f.github.io/main/vmess.config',
'https://raw.githubusercontent.com/shabane/kamaji/master/hub/b64/merged.txt',
'https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt',
'https://raw.githubusercontent.com/sharje63/v2ray_collection/main/ver2',
'https://raw.githubusercontent.com/shbioc/clash/main/aaa01.yaml',
'https://raw.githubusercontent.com/shiran588/jiedian/main/6.11.yaml',
'https://raw.githubusercontent.com/shiran588/jiedian/main/jd1.txt',
'https://raw.githubusercontent.com/SnapdragonLee/SystemProxy/master/dist/clash_config.yaml',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/grpc',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/tcp',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/networks/ws',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/hysteria',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/reality',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/shadowsocks',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/trojan',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/vless',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/protocols/vmess',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/security/non-tls',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/channels/security/tls',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/at/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ca/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/de/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ee/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/es/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/fr/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/gb/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/hk/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ie/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ir/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/jp/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/kr/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/kz/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/na/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/nl/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/pl/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/ru/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/se/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/sg/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/tr/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/us/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/grpc',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/tcp',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/networks/ws',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/hysteria',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/reality',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/shadowsocks',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/trojan',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vless',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vmess',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/security/non-tls',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/channels',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/mixed',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/splitted/subscribe',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/layers/ipv4',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/grpc',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/tcp',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/networks/ws',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/reality',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/shadowsocks',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/trojan',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/vless',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/protocols/vmess',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/security/non-tls',
'https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/subscribe/security/tls',
# 'https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml',
'https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub',
'https://raw.githubusercontent.com/ssrsub/ssr/master/trojan',
'https://raw.githubusercontent.com/ssrsub/ssr/master/V2Ray',
'https://raw.githubusercontent.com/Strongmiao168/v2ray/main/1203',
'https://raw.githubusercontent.com/sun9426/sun9426.github.io/main/subscribe/Clash.yaml',
'https://raw.githubusercontent.com/sun9426/sun9426.github.io/main/subscribe/v2ray.txt',
'https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/output/converted.txt',
'https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/submerge/converted.txt',
'https://raw.githubusercontent.com/Surfboardv2ray/Subs/main/Raw',
'https://raw.githubusercontent.com/Surfboardv2ray/Vfarid-fix/main/sub64',
'https://raw.githubusercontent.com/suweisheng/test/main/clash.yaml',
'https://raw.githubusercontent.com/Syavar/V2ray-Configs/main/OK_google.com.txt',
'https://raw.githubusercontent.com/szkjw/HKTW503/main/README.md',
'https://raw.githubusercontent.com/Tenerome/v2ray/main/vmess.txt',
'https://raw.githubusercontent.com/theGreatPeter/v2rayNodes/main/nodes.txt',
'https://raw.githubusercontent.com/tjyu010/jiedian/main/21',
'https://raw.githubusercontent.com/tony0392/clash/main/clash.yaml',
'https://raw.githubusercontent.com/ts-sf/fly/main/clash',
'https://raw.githubusercontent.com/ts-sf/fly/main/v2',
'https://raw.githubusercontent.com/txmiaomiaowu/openitr/main/long',
'https://raw.githubusercontent.com/udonlover420/lsd-cf-sub/main/lsd.txt',
'https://raw.githubusercontent.com/V2raayNGConfig/KhaliJ/main/V2ray.txt',
'https://raw.githubusercontent.com/VahidSkndri/sub-pan/main/Sub-panpan',
'https://raw.githubusercontent.com/Vauth/node/main/Main',
'https://raw.githubusercontent.com/Vauth/node/main/Master',
'https://raw.githubusercontent.com/visiti/clash-node/main/clash-node.yaml',
'https://raw.githubusercontent.com/voken1/AutoSSR/master/recent',
'https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent',
'https://raw.githubusercontent.com/vpei/free-node-1/main/o/proxies.txt',
'https://raw.githubusercontent.com/vpnmarket/sub/main/hiddify1.txt',
'https://raw.githubusercontent.com/vpnmarket/sub/main/hiddify2.txt',
'https://raw.githubusercontent.com/vpnmarket/sub/main/hiddify3.txt',
'https://raw.githubusercontent.com/VpnNetwork01/vpn-net/main/README.md',
'https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription_num',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription_try',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1.yaml',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription4',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription5',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription6',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription7',
'https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription8',
'https://raw.githubusercontent.com/webdao/v2ray/master/nodes.txt',
'https://raw.githubusercontent.com/wei/ssr-scraper/master/subscribe.txt',
'https://raw.githubusercontent.com/WilliamStar007/ClashX-V2Ray-TopFreeProxy/main/combine/clash.config.yaml',
'https://raw.githubusercontent.com/WilliamStar007/ClashX-V2Ray-TopFreeProxy/main/combine/v2ray.config.txt',
'https://raw.githubusercontent.com/wlswagger/jiedian/main/5.11',
'https://raw.githubusercontent.com/wrfree/free/main/README.md',
'https://raw.githubusercontent.com/wrfree/free/main/v2',
'https://raw.githubusercontent.com/wwwzywasia/free/main/sub',
'https://raw.githubusercontent.com/wyq00000/test/main/data/test1',
'https://raw.githubusercontent.com/xbuffer/ClashData/main/Eternity.yaml',
'https://raw.githubusercontent.com/xiyaowong/freeFQ/main/v2ray',
'https://raw.githubusercontent.com/XYZMojtaba/sub/main/mci.txt',
'https://raw.githubusercontent.com/yaney01/autoproxy/master/Eternity',
'https://raw.githubusercontent.com/yaney01/chromego_merge/main/sub/merged_proxies_new.yaml',
'https://raw.githubusercontent.com/yaney01/Yaney01/main/README.md',
'https://raw.githubusercontent.com/yaney01/Yaney01/main/temporary',
'https://raw.githubusercontent.com/yaney01/Yaney01/main/yaney_01',
'https://raw.githubusercontent.com/YasserDivaR/pr0xy/main/mycustom1.txt',
'https://raw.githubusercontent.com/YasserDivaR/pr0xy/main/ShadowSocks2021.txt',
'https://raw.githubusercontent.com/YasserDivaR/pr0xy/main/winformClash.yaml',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/mix',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/shadowsocks',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vless',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vmess',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/trojan',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/vless',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/vmess',
'https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/base64/mix',
'https://raw.githubusercontent.com/yebekhe/TVC/main/subscriptions/xray/normal/mix',
'https://raw.githubusercontent.com/yebekhe/V2Hub/main/merged_base64',
'https://raw.githubusercontent.com/yebekhe/V2Hub/main/Split/Base64/shadowsocks',
'https://raw.githubusercontent.com/yebekhe/V2Hub/main/Split/Base64/trojan',
'https://raw.githubusercontent.com/yebekhe/V2Hub/main/Split/Base64/vless',
'https://raw.githubusercontent.com/yebekhe/V2Hub/main/Split/Base64/vmess',
'https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/mixed_iran.txt',
'https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/ss_iran.txt',
'https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/trojan_iran.txt',
'https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/vless_iran.txt',
'https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/vmess_iran.txt',
'https://raw.githubusercontent.com/youkai0100/youkai/master/Eternity.yaml',
'https://raw.githubusercontent.com/youkai0100/youkai/master/README.md',
'https://raw.githubusercontent.com/yukikazemiyuki/dingyue/main/clash.yaml',
'https://raw.githubusercontent.com/yyyr-otz/tele-providers-collector/master/script/raw/protocols/vless.txt',
'https://raw.githubusercontent.com/yyyr-otz/tele-providers-collector/master/script/raw/protocols/vless-CDN.txt',
'https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml',
'https://raw.githubusercontent.com/zhlx2835/freefq/main/clash.yaml',
'https://raw.githubusercontent.com/zhlx2835/freefq/main/v2',
'https://raw.githubusercontent.com/zjfb/SubCrawler/main/sub/share/all',
'https://raw.githubusercontent.com/zjr13808836946/zjr_clash/main/V2_SSR_M',
'https://raw.githubusercontent.com/zonghewang/get_subscribe/main/subscribe/clash.yml',
'https://raw.githubusercontent.com/ZY-404/v2ray/main/v2ray.txt',
'https://raw.githubusercontent.com/ZywChannel/free/main/sub',
'https://raw.githubusercontent.com/zyzmzyz/free-nodes/master/Clash.yml',
'https://raw.githubusercontent.com/zzz6839/SubCrawler/main/sub/share/all',
'https://raw.githubusercontent.com/9Knight9n/v2ray-aggregator/main/merged_24h.txt',
'https://raw.githubusercontent.com/amirhosein24/v2ray-config-farmer/raw/main/zout.txt',
'https://raw.githubusercontent.com/0x24a/FreeNodes/main/subs/main.txt',
'https://raw.githubusercontent.com/Sadeghi85/tg-v2ray/main/generated/subs/all',
'https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/raw/main/sublinks/mix.txt',
'https://raw.githubusercontent.com/dimzon/scaling-sniffle/main/all-ip-resolve-sort.txt',
'https://raw.githubusercontent.com/dimzon/scaling-sniffle/main/all-domains-dedup-sort.txt',
'https://raw.githubusercontent.com/dimzon/scaling-sniffle/main/all-domains-sort.txt',
'https://raw.githubusercontent.com/dimzon/scaling-sniffle/main/all-sort.txt',
'https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_base64_Sub.txt',
'https://raw.githubusercontent.com/mfbpn/tg_mfbpn_sub/main/trial.yaml',
'https://raw.githubusercontent.com/mheidari98/.proxy/main/all',
'https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml',
'https://raw.githubusercontent.com/barry-far/V2ray-Configs/main/All_Configs_base64_Sub.txt',
'https://raw.gitmirror.com/ripaojiedian/freenode/main/sub',
'https://raw.githubusercontent.com/jlhmomo/juelaohai/main/gaOIHsiushdg11132',
'https://github.com/qjlxg/YBSub/raw/refs/heads/master/sub/share/available',
'https://github.com/qjlxg/YBSub/raw/refs/heads/master/sub/share/v2',
'https://mrpooyax.camdvr.org/api/ramezan/lena.php?sub=1',
'https://mrpooyax.camdvr.org/api/ramezan/run.php?sub=1',
'https://mrpooyax.camdvr.org/api/ramezan/alpha.php?sub=1',
'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/donated',
'https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub',
'https://raw.githubusercontent.com/IranianCypherpunks/sub/main/config',
'https://raw.githubusercontent.com/sashalsk/V2Ray/main/V2Config',
'https://mrpooya.top/api/lena.php',
'https://raw.githubusercontent.com/freev2rayconfig/V2RAY_SUBSCRIPTION_LINK/main/v2rayconfigs.txt',
'https://github.com/barry-far/V2ray-Configs/raw/refs/heads/main/All_Configs_Sub.txt',
'https://github.com/shabane/kamaji/raw/refs/heads/master/hub/b64/merged.txt',
'https://github.com/coldwater-10/V2ray-Config/raw/refs/heads/main/All_Configs_Sub.txt',
'https://github.com/darknessm427/IranConfigCollector/raw/refs/heads/main/Allconfig',
'https://github.com/skywrt/v2ray-configs/raw/refs/heads/main/All_Configs_Sub.txt',
'https://github.com/DivineGlaive/TGParse/raw/refs/heads/main/configtg.txt',
'https://github.com/3yed82/TVC/raw/refs/heads/main/config.txt',
'https://github.com/qjlxg/genode/raw/refs/heads/main/public/all.txt',
'https://github.com/qjlxg/ss/raw/refs/heads/master/list.txt',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/all',
'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/available',
'https://github.com/qjlxg/hy2/raw/refs/heads/main/configtg.txt',
'https://github.com/qjlxg/Ray/raw/refs/heads/main/config.txt',
'https://github.com/qjlxg/py/raw/refs/heads/main/data/v2ray.txt',
'https://github.com/coldwater-10/V2ray-Configs/raw/refs/heads/main/All_Configs_Sub.txt',
'https://raw.githubusercontent.com/shabane/kamaji/master/hub/b64/merged.txt'
    ]
    dir_links = [
        'https://raw.githubusercontent.com/IranianCypherpunks/sub/main/config',
        'https://raw.githubusercontent.com/sashalsk/V2Ray/main/V2Config',
        'https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.txt',
        'https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/normal/mix',
        'https://mrpooya.top/api/lena.php',
        'https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/all.txt',
        'https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/row-url/actives.txt',
        'https://raw.githubusercontent.com/freev2rayconfig/V2RAY_SUBSCRIPTION_LINK/main/v2rayconfigs.txt',
        'https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt',
        'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/tr',
        'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/ss',
        'https://github.com/qjlxg/Sub2/raw/refs/heads/main/sub/share/ssr',
        'https://github.com/qjlxg/ss/raw/refs/heads/master/list.txt' 
        
    
       ]

    decoded_links = decode_links(links)
    decoded_dir_links = decode_dir_links(dir_links)
    merged_configs = decoded_links + decoded_dir_links
    output_folder = os.path.abspath(os.path.join(os.getcwd(), '..'))
    base64_folder = os.path.join(output_folder, 'Base64')

    # Delete existing output files
    filename = os.path.join(output_folder, f'All_Configs_Sub.txt')
    filename1 = os.path.join(output_folder, f'All_Configs_base64_Sub.txt')
    if os.path.exists(filename):
        os.remove(filename)
    if os.path.exists(filename1):
        os.remove(filename1)
    for i in range(20):
        filename = os.path.join(output_folder, f'Config list{i}.txt')
        if os.path.exists(filename):
            os.remove(filename)
        filename1 = os.path.join(base64_folder, f'Config list{i}_base64.txt')
        if os.path.exists(filename1):
            os.remove(filename1)

    # Remove TLS configs file
    filename = os.path.join(output_folder, f'Config_TLS.txt')
    if os.path.exists(filename):
        os.remove(filename)

    # Write merged configs to output file
    output_file = os.path.join(output_folder, 'All_Configs_Sub.txt')
    with open(output_file, 'w') as f:
        for config in merged_configs:
            f.write(config + '\n')

    # Split merged configs into files with no more than 1000 configs per file
    with open(output_file, 'r') as f:
        lines = f.readlines()
    num_lines = len(lines)
    max_lines_per_file = 3680
    num_files = (num_lines + max_lines_per_file - 1) // max_lines_per_file
    for i in range(num_files):
        start_index = i * max_lines_per_file
        end_index = (i + 1) * max_lines_per_file
        filename = os.path.join(output_folder, f'Config list{i+1}.txt')
        with open(filename, 'w') as f:
            for line in lines[start_index:end_index]:
                f.write(line)
                
    # Encode to base64 and save merged configs to a single file
    encoded_merged_configs = base64.b64encode("\n".join(merged_configs).encode()).decode()
    output_file = os.path.join(output_folder, 'All_Configs_base64_Sub.txt')
    with open(output_file, 'w') as f:
        f.write(encoded_merged_configs)

    # Encode and save each Sub{i+1}.txt file to base64_folder as Sub{i+1}_base64.txt
    for i in range(num_files):
        input_filename = os.path.join(output_folder, f'Config list{i+1}.txt')
        output_filename = os.path.join(base64_folder, f'Config list{i+1}_base64.txt')

        with open(input_filename, 'r') as input_file:
            config_data = input_file.read()
        
        encoded_config = base64.b64encode(config_data.encode()).decode()

        with open(output_filename, 'w') as output_file:
            output_file.write(encoded_config)

    # Take all tls enabled configs and save them to Configs_TLS.txt
    tls_file = os.path.join(output_folder, f"Configs_TLS.txt")
    with open(tls_file, "w") as f:
        for line in lines:
            if "security=tls" in line:
                f.write(line)

    # Take all tls enabled configs from tls_file, encode and save them to Configs_TLS_base64.txt
    tls_encoded_file = os.path.join(output_folder, f'Config_TLS_base64.txt')
    with open(tls_file, 'r') as input_file:
        tls_config_data = input_file.read()
    
    encoded_tls_config = base64.b64encode(tls_config_data.encode()).decode()

    with open(tls_encoded_file, 'w') as output_file:
        output_file.write(encoded_tls_config)

    
if __name__ == "__main__":
    main()
